//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenusDoors.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="This field is required")]
        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string Password { get; set; }
        public int IdType { get; set; }
        public int IdPerson { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorUser { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModificationUser { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
